### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by SzotsGabor** [Ilya-Ruk/RukChess#1]
Hello Ilya,

It is not clear to me if these are different engines or one engine with different evaluation. If I decided to test it I'd prefer to test only one engine and I am not sure which it should be. To put it clearly, exactly what files shall I download?

Gabor Szots,
CCRL testing group

**Comment by Ilya-Ruk** [comment]
Hello Gabor,

There are four executable files in the release. Each file is an engine with one evaluation function. For testing, I recommend taking RukChess 3.0 NNUE2.exe and the network file rukchess.nnue.

Ilya Rukavishnikov

**Comment by SzotsGabor** [comment]
I recommend using only the NNUE2 version (deleting the rest) or name each of the four versions differently. Otherwise, all having the same name,  how could we tell which version was used in a tournament?

**Comment by Ilya-Ruk** [comment]
Hello Gabor,

In the new release (https://github.com/Ilya-Ruk/RukChess/releases/tag/3.0.12), I added the display of the name of the evaluation function in the UCI "id name" field. Will this be enough to uniquely identify the engine?

Ilya Rukavishnikov

**Comment by SzotsGabor** [comment]
Hi Ilya,

Yes, it's enough. However, most probably we will use only the NNUE2 version (as we did up to now). I'm going to tell Ray, who maintains our lists, to include an explaining note that it was NNUE2.

BTW, what are the differences between 3.0 and 3.0.12?

**Comment by Ilya-Ruk** [comment]
Thank you Gabor!

>what are the differences between 3.0 and 3.0.12?

1. Corrected SEE
2. Search speed optimization
3. NNUE2 speed optimization
4. Added evaluation function name in program name
5. Removed king side (KS) and king quadrant (KQ) architectures from NNUE2
6. Reworked tuning code (for Toga evaluation function only)

I shall add CHANGELOG file a bit later

**Comment by Ilya-Ruk** [comment]
Hello Gabor,

I added CHANGELOG file into project. Can I closed this issue?

Ilya Rukavishnikov

**Comment by SzotsGabor** [comment]
Of course you can. Thank you.
