### ISSUE TITLE
Networks

### ISSUE THREAD

**Issue by SzotsGabor** [Ilya-Ruk/RukChess#2]
Hi Ilya,

I am still not sure how to use the networks.

Are the networks for version 3.0.15 NNUE2 and 3.0.16 NNUE2 different? If they are different, how can I use both versions at the same time? If the network must be named rukchess.nnue then I have to put different versions in different folders, which I would rather not do.

I think a parameter for the NNUE file would solve this issue. Then I could chose different networks for different vversions.
E.g. "option name EvalFile type string default <empty>".
Then the engine could be started without a file. Now it cannot because it exit when it does not find rukchess.nnue.

Regards,
Gabor

**Comment by Ilya-Ruk** [comment]
Hello Gabor!

>Are the networks for version 3.0.15 NNUE2 and 3.0.16 NNUE2 different?

Yes, the networks are different.

>If they are different, how can I use both versions at the same time?

I added UCI option NnueFile to RukChess 3.0.17. I'm planning to release it next week.

Best regards,
Ilya

**Comment by Ilya-Ruk** [comment]
Hello Gabor!

I have released RukChess 3.0.17 (https://github.com/Ilya-Ruk/RukChess/releases/tag/3.0.17).

Best regards,
Ilya

**Comment by SzotsGabor** [comment]
Hi Ilya,

I have started a tournament with RukChess 3.0.17 (NNUE2). Alas, first results are not particularly promising. We'll see how it develops.

BTW, you might make the name of the net file match the name of the exe. E.g. rukchess3017.nnue. Otherwise the user will have to rename it during saving, to avoid overwriting the previous nnue file. Also, you might make the deafault file name different for different versions of RukChess. Just an idea.

**Comment by Ilya-Ruk** [comment]
Hello Gabor!

>I have started a tournament with RukChess 3.0.17 (NNUE2). Alas, first results are not particularly promising. We'll see how it develops.

I see the results for the RukChess 3.0.17 (NNUE2) on https://www.computerchess.org.uk/ccrl/404/cgi/compare_engines.cgi?family=RukChess&print=Rating+list&print=Results+table&print=LOS+table&print=Ponder+hit+table&print=Eval+difference+table&print=Comopp+gamenum+table&print=Overlap+table&print=Score+with+common+opponents and I am also very surprised. My tests showed this result (tc=120+1)

Score of RukChess 3.0.17 NNUE2 vs RukChess 3.0.15 NNUE2: 307 - 202 - 491  [0.552] 1000
...      RukChess 3.0.17 NNUE2 playing White: 132 - 126 - 242  [0.506] 500
...      RukChess 3.0.17 NNUE2 playing Black: 175 - 76 - 249  [0.599] 500
...      White vs Black: 208 - 301 - 491  [0.454] 1000
Elo difference: 36.6 +/- 15.4, LOS: 100.0 %, DrawRatio: 49.1 %

Are you sure that the network file corresponding to the program version was used in the CCRL tests?

>BTW, you might make the name of the net file match the name of the exe. E.g. rukchess3017.nnue. Otherwise the user will have to rename it during saving, to avoid overwriting the previous nnue file. Also, you might make the deafault file name different for different versions of RukChess. Just an idea.

Thanks, I will implement this in the next version.

Best regards,
Ilya

**Comment by SzotsGabor** [comment]
Yes. This is the engine file for RukChess which I used under the Shredder GUI:

[ENGINE]
Name=RukChess 3.0.17 64-bit
Author=Ilya Rukavishnikov
Filename=E:\Sakk\UCI-engines\RukChess\RukChess_3.0.17-x64.exe
[OPTIONS]
BookFile=<empty>
NnueFile=rukchess3017.nnue

rukchess3017.nnue is the renamed nnue file that comes with this version.

**Comment by Ilya-Ruk** [comment]
Hello Gabor!

I have released RukChess 3.0.18 (https://github.com/Ilya-Ruk/RukChess/releases/tag/3.0.18). For details, see [CHANGELOG.md](https://github.com/Ilya-Ruk/RukChess/blob/master/CHANGELOG.md).

Some results of my tests

RukChess 3.0.18 NNUE2 ([Net 070, Epoch 120, Hash 0x755b16a94877](https://github.com/Ilya-Ruk/RukChessNets/blob/master/Nets%20070/rukchess_120.nnue)) vs RukChess 3.0.15 NNUE2 ([Net 122, Epoch 081, Hash 0x7cf57d4dc994](https://github.com/Ilya-Ruk/RukChessNets/blob/master/Nets%20122/rukchess_081.nnue))

tc=120+1

Score of RukChess 3.0.18 NNUE2 vs RukChess 3.0.15 NNUE2: 300 - 171 - 529  [0.565] 1000
...      RukChess 3.0.18 NNUE2 playing White: 117 - 111 - 272  [0.506] 500
...      RukChess 3.0.18 NNUE2 playing Black: 183 - 60 - 257  [0.623] 500
...      White vs Black: 177 - 294 - 529  [0.442] 1000
Elo difference: 45.1 +/- 14.7, LOS: 100.0 %, DrawRatio: 52.9 %

tc=15+0.15

Score of RukChess 3.0.18 NNUE2 vs RukChess 3.0.15 NNUE2: 356 - 237 - 407  [0.559] 1000
...      RukChess 3.0.18 NNUE2 playing White: 166 - 127 - 207  [0.539] 500
...      RukChess 3.0.18 NNUE2 playing Black: 190 - 110 - 200  [0.580] 500
...      White vs Black: 276 - 317 - 407  [0.479] 1000
Elo difference: 41.5 +/- 16.6, LOS: 100.0 %, DrawRatio: 40.7 %

Best regards,
Ilya

**Comment by CPagador** [comment]
> Hello Gabor!
> 
> I have released RukChess 3.0.18 (https://github.com/Ilya-Ruk/RukChess/releases/tag/3.0.18). For details, see [CHANGELOG.md](https://github.com/Ilya-Ruk/RukChess/blob/master/CHANGELOG.md).
> 

Hi,

It is not possible to download the NNUE2 net:

https://github.com/Ilya-Ruk/RukChessNets/blob/master/Nets%20122/rukchess_081.nnue

I got an error message.

Best regards,
Carlos

**Comment by Ilya-Ruk** [comment]
Hello, Carlos!

I uploaded Nets 122 files and tests.

Best regards,
Ilya

**Comment by CPagador** [comment]
Great, thank you Ilya.
